To generate an Ansible playbook for provisioning a Docker container, you can follow these steps:

1. Install Ansible on your system. You can refer to the official Ansible documentation for installation instructions.
2. Create a new directory for your Ansible project.
3. Inside the project directory, create a file named `playbook.yml`.
4. Open `playbook.yml` in a text editor and add the following content:

```yaml
---
- hosts: localhost
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      
    - name: Start Docker service
      service:
        name: docker
        state: started
        
    - name: Pull Docker image
      docker_image:
        name: {{ image_name }}
      
    - name: Create Docker container
      docker_container:
        name: {{ container_name }}
        image: {{ image_name }}
        state: started
```

5. Replace `{{ image_name }}` with the name of the Docker image you want to use, and `{{ container_name }}` with the desired name for your Docker container.
6. Save and close `playbook.yml`.
7. Run the following command to execute the Ansible playbook:

```
ansible-playbook playbook.yml
```

This playbook will install Docker, start the Docker service, pull the specified Docker image, and create a container from that image.

Please note that this is a simplified example and you may need to modify the playbook to fit your specific requirements.