Here is an example of a Kubernetes YAML file that creates an ELK (Elasticsearch, Logstash, and Kibana) application pod with a namespace, deployment, secrets, configmap, service, and route:

```yaml
# Define the namespace
apiVersion: v1
kind: Namespace
metadata:
  name: elk-namespace

---

# Define the deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elk-deployment
  namespace: elk-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elk-app
  template:
    metadata:
      labels:
        app: elk-app
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.6.2
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/pipeline/
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.6.2
          ports:
            - containerPort: 5601

      volumes:
        - name: logstash-config
          configMap:
            name: logstash-configmap

---

# Define the secrets
apiVersion: v1
kind: Secret
metadata:
  name: elk-secrets
  namespace: elk-namespace
type: Opaque
data:
  username: <<username_base64_encoded>>
  password: <<password_base64_encoded>>

---

# Define the configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: elk-namespace
data:
  logstash.conf: |
    <<logstash_configuration_here>>

---

# Define the service
apiVersion: v1
kind: Service
metadata:
  name: elk-service
  namespace: elk-namespace
spec:
  selector:
    app: elk-app
  ports:
    - name: elasticsearch
      port: 9200
    - name: logstash
      port: 5000
    - name: kibana
      port: 5601

---

# Define the route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: elk-route
  namespace: elk-namespace
spec:
  host: elk.example.com
  to:
    kind: Service
    name: elk-service

```

Note: Please replace `<<placeholders>>` with your actual values.