
apiVersion: v1
kind: Namespace
metadata:
  name: app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: quay.io/centos7/nginx-120-centos7
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namespace: app
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: helloworld-route
  namespace: app
spec:
  to:
    kind: Service
    name: helloworld-service
  tls:
    termination: edge
