
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namepspace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: quay.io/nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namepspace: app
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: helloworld-route
  namepspace: app
spec:
  to:
    kind: Service
    name: helloworld-service
  tls:
    termination: edge
