
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: app

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: quay.io/centos7/nginx-120-centos7
          ports:
            - containerPort: 80

---
# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: web-app-secrets
  namespace: app
type: Opaque
data:
  username: YWRtaW4=     # Base64 encoded value for 'admin'
  password: cGFzc3dvcmQ= # Base64 encoded value for 'password'

---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-config
  namespace: app
data:
  config.ini: |
    [server]
    port = 8080
    timezone = UTC

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: app
spec:
  selector:
    app: web-app
  ports:
    - name: http
      port: 80
      targetPort: 80

---
# Route (Assuming OpenShift)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: web-app-route
  namespace: app
spec:
  to:
    kind: Service
    name: web-app-service
