---
apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: app
spec:
  containers:
    - name: web-container
      image: registry.ocp4.example.com:8443/redhattraining/podman-info-times:v0.1
      ports:
        - containerPort: 80


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web-container
          image: registry.ocp4.example.com:8443/redhattraining/podman-info-times:v0.1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app
type: Opaque
data:
  username: test
  password: test


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
data:
  app.properties: |
    key1=red
    key2=blue


---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: app
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: app
spec:
  rules:
    - host: bluetest.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  number: 80
